### ISSUE TITLE
species_id

### ISSUE THREAD

**Issue by smnorris** [poissonconsulting/fishbc#1]
Thanks for publishing this, it is too bad it is not available via the Data Catalogue. Going forward, I'll grab `WHSE_FISH.SPECIES_CD` from this csv.

To make things a bit easier when querying by species in postgres, it would be nice to have a species_id column. I see there is already an integer column in https://github.com/poissonconsulting/fishbc/blob/master/data-raw/whse_fish_species_cd/whse_fish_species_cd.csv, it just lacks a name in the header.  Would it be reasonable to label this column as `species_id` and use it as the primary key?

**Comment by joethorley** [comment]
closed by pull request #2
